# Form implementation generated from reading ui file 'Config.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DarkCheckBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.DarkCheckBox.setGeometry(QtCore.QRect(170, 180, 76, 20))
        self.DarkCheckBox.setObjectName("DarkCheckBox")
        self.WhiteCheck = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.WhiteCheck.setGeometry(QtCore.QRect(170, 200, 101, 20))
        self.WhiteCheck.setAutoFillBackground(False)
        self.WhiteCheck.setChecked(True)
        self.WhiteCheck.setObjectName("WhiteCheck")
        self.IdiomaBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.IdiomaBox.setGeometry(QtCore.QRect(130, 50, 141, 41))
        self.IdiomaBox.setObjectName("IdiomaBox")
        self.IdiomaBox.addItem("")
        self.IdiomaBox.addItem("")
        self.IdiomaBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 300, 151, 75))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Configuracoes"))
        self.DarkCheckBox.setText(_translate("MainWindow", "Dark Mode"))
        self.WhiteCheck.setText(_translate("MainWindow", "White mode"))
        self.IdiomaBox.setItemText(0, _translate("MainWindow", "Portugues"))
        self.IdiomaBox.setItemText(1, _translate("MainWindow", "Ingles"))
        self.IdiomaBox.setItemText(2, _translate("MainWindow", "Espanhol"))
        self.pushButton.setText(_translate("MainWindow", "Confirmar configuraçoes"))
