# Form implementation generated from reading ui file 'PaginaInicial.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 499)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LivrosBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LivrosBtn.setGeometry(QtCore.QRect(40, 40, 121, 111))
        self.LivrosBtn.setObjectName("LivrosBtn")
        self.CarrinhoBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CarrinhoBtn.setGeometry(QtCore.QRect(210, 40, 121, 111))
        self.CarrinhoBtn.setObjectName("CarrinhoBtn")
        self.ContaBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ContaBtn.setGeometry(QtCore.QRect(380, 40, 121, 111))
        self.ContaBtn.setObjectName("ContaBtn")
        self.ConfigBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ConfigBtn.setGeometry(QtCore.QRect(110, 200, 121, 111))
        self.ConfigBtn.setObjectName("ConfigBtn")
        self.GuideBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GuideBtn.setGeometry(QtCore.QRect(310, 200, 121, 111))
        self.GuideBtn.setObjectName("GuideBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVerificar_Carrinho = QtGui.QAction(parent=MainWindow)
        self.actionVerificar_Carrinho.setObjectName("actionVerificar_Carrinho")
        self.actionPrincipais_Livros_do_dia = QtGui.QAction(parent=MainWindow)
        self.actionPrincipais_Livros_do_dia.setObjectName("actionPrincipais_Livros_do_dia")
        self.actionPrincipais_livros_para_voce = QtGui.QAction(parent=MainWindow)
        self.actionPrincipais_livros_para_voce.setObjectName("actionPrincipais_livros_para_voce")
        self.actionLivros_que_est_o_alugados = QtGui.QAction(parent=MainWindow)
        self.actionLivros_que_est_o_alugados.setObjectName("actionLivros_que_est_o_alugados")
        self.actionLivros_que_voce_alugou = QtGui.QAction(parent=MainWindow)
        self.actionLivros_que_voce_alugou.setObjectName("actionLivros_que_voce_alugou")
        self.actionpreferencias = QtGui.QAction(parent=MainWindow)
        self.actionpreferencias.setObjectName("actionpreferencias")
        self.actionconfigura_oes_da_conta = QtGui.QAction(parent=MainWindow)
        self.actionconfigura_oes_da_conta.setObjectName("actionconfigura_oes_da_conta")
        self.actionConfigura_oes_gerais = QtGui.QAction(parent=MainWindow)
        self.actionConfigura_oes_gerais.setObjectName("actionConfigura_oes_gerais")
        self.actionComo_nosso_software_funciona = QtGui.QAction(parent=MainWindow)
        self.actionComo_nosso_software_funciona.setObjectName("actionComo_nosso_software_funciona")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pagina inicial"))
        self.LivrosBtn.setText(_translate("MainWindow", "Livros Disponiveis"))
        self.CarrinhoBtn.setText(_translate("MainWindow", "Carrinho"))
        self.ContaBtn.setText(_translate("MainWindow", "Conta"))
        self.ConfigBtn.setText(_translate("MainWindow", "Configuraçoes"))
        self.GuideBtn.setText(_translate("MainWindow", "Como funciona"))
        self.actionVerificar_Carrinho.setText(_translate("MainWindow", "Verificar Carrinho"))
        self.actionPrincipais_Livros_do_dia.setText(_translate("MainWindow", "Principais Livros do dia"))
        self.actionPrincipais_livros_para_voce.setText(_translate("MainWindow", "Principais livros para voce"))
        self.actionLivros_que_est_o_alugados.setText(_translate("MainWindow", "Livros que estão alugados"))
        self.actionLivros_que_voce_alugou.setText(_translate("MainWindow", "Livros que voce alugou"))
        self.actionpreferencias.setText(_translate("MainWindow", "preferencias"))
        self.actionconfigura_oes_da_conta.setText(_translate("MainWindow", "Configuraçoes da conta"))
        self.actionConfigura_oes_gerais.setText(_translate("MainWindow", "Configuraçoes gerais"))
        self.actionComo_nosso_software_funciona.setText(_translate("MainWindow", "Como nosso software funciona"))
