# Form implementation generated from reading ui file 'esqueciSenha.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 300, 151, 51))
        self.pushButton.setObjectName("pushButton")
        self.EmailInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.EmailInput.setGeometry(QtCore.QRect(200, 60, 161, 22))
        self.EmailInput.setObjectName("EmailInput")
        self.NomeInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NomeInput.setGeometry(QtCore.QRect(200, 120, 161, 22))
        self.NomeInput.setObjectName("NomeInput")
        self.EmailLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.EmailLabel.setGeometry(QtCore.QRect(70, 60, 111, 21))
        self.EmailLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.EmailLabel.setObjectName("EmailLabel")
        self.NomeLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.NomeLabel.setGeometry(QtCore.QRect(130, 120, 49, 16))
        self.NomeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.NomeLabel.setObjectName("NomeLabel")
        self.NovaSenhaInput = QtWidgets.QLabel(parent=self.centralwidget)
        self.NovaSenhaInput.setGeometry(QtCore.QRect(80, 250, 211, 20))
        self.NovaSenhaInput.setText("")
        self.NovaSenhaInput.setObjectName("NovaSenhaInput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Recuperar Senha"))
        self.EmailLabel.setText(_translate("MainWindow", "Informe o email:"))
        self.NomeLabel.setText(_translate("MainWindow", "Nome:"))
