# Form implementation generated from reading ui file 'Conta.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SenhaBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SenhaBtn.setGeometry(QtCore.QRect(150, 160, 131, 71))
        self.SenhaBtn.setObjectName("SenhaBtn")
        self.dadosBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dadosBtn.setGeometry(QtCore.QRect(360, 160, 131, 71))
        self.dadosBtn.setObjectName("dadosBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conta"))
        self.SenhaBtn.setText(_translate("MainWindow", "alterar senha"))
        self.dadosBtn.setText(_translate("MainWindow", "Mostrar Dados"))
